Enhanced CICD

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -9,7 +9,8 @@ on:
 jobs:
   linting:
     runs-on: ubuntu-latest
-
+    permissions:
+      pull-requests: write
     steps:
       - name: checkout code
         uses: actions/checkout@v2
@@ -24,12 +25,31 @@ jobs:
           pip install flake8
 
       - name: Run flake8
+        id: flake8
         run: |
-          flake8
+          flake8 > flake8-report.md
+          if [ -s flake8-report.md ]; then exit 1; fi
+
+      - name: Post flake8 report
+        if: always() && steps.flake8.conclusion == 'failure'
+        uses: actions/github-script@v5
+        with:
+          github-token: ${{secrets.GITHUB_TOKEN}}
+          script: |
+            const fs = require('fs');
+            const flake8Report = fs.readFileSync('flake8-report.md', 'utf8');
+            github.rest.issues.createComment({
+              issue_number: context.issue.number,
+              owner: context.repo.owner,
+              repo: context.repo.repo,
+              body: `# Linting Failed:\n\`\`\`\n${flake8Report}\n\`\`\``
+            });
 
   unit-testing:
     runs-on: ubuntu-latest
     needs: linting
+    permissions:
+      pull-requests: write
     steps:
       - name: checkout code
         uses: actions/checkout@v2
@@ -50,8 +70,24 @@ jobs:
       - name: start localstack
         run: docker-compose up -d localstack
 
-      - name: do pytest
-        run: pytest
+      - name: Run pytest
+        id: pytest
+        run: pytest --md report.md
+
+      - name: Post pytest report
+        uses: actions/github-script@v5
+        if: always()
+        with:
+          github-token: ${{secrets.GITHUB_TOKEN}}
+          script: |
+            const fs = require('fs');
+            const testResults = fs.readFileSync('report.md', 'utf8');
+            github.rest.issues.createComment({
+              issue_number: context.issue.number,
+              owner: context.repo.owner,
+              repo: context.repo.repo,
+              body: `# Test Results:\n\`\`\`\n${testResults}\n\`\`\``
+            });
 
   assign-reviewer:
     runs-on: ubuntu-latest
